import React from 'react';
import { WrappedData } from '../../wrappedQueries';
import { Stat } from './components/Stat';
import { BarRow } from './components/BarRow';
import { SectionTitle } from './components/SectionTitle';

interface WrappedCardProps {
  data: WrappedData;
  title: string;
  subtitle: string;
}

/**
 * The main JSX template for the Wrapped image.
 * 
 * IMPORTANT satori constraints:
 * - ONLY flexbox layout works. No grid, no float, no position absolute except with parent relative.
 * - Every element with multiple children MUST have `display: flex`.
 * - Tailwind classes work via the `tailwindConfig` option, but plain inline styles are simpler — use inline styles.
 */
export const WrappedCard: React.FC<WrappedCardProps> = ({ data, title, subtitle }) => {
  const maxMessages = data.topUsers.length > 0 ? data.topUsers[0].count : 1;

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        width: '1200px',
        height: '630px',
        background: 'linear-gradient(135deg, #23272A 0%, #2C2F33 100%)',
        padding: '40px',
        color: '#FFFFFF',
        fontFamily: 'Inter',
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', flexDirection: 'column', marginBottom: '30px' }}>
        <div style={{ display: 'flex', fontSize: '64px', fontWeight: 'bold', letterSpacing: '-2px' }}>
          {title}
        </div>
        <div style={{ display: 'flex', fontSize: '24px', color: '#5865F2', fontWeight: 'bold' }}>
          {subtitle}
        </div>
      </div>

      <div style={{ display: 'flex', flex: 1, gap: '40px' }}>
        {/* Left Column: Stats Grid */}
        <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
          <SectionTitle>Server Snapshot</SectionTitle>
          <div style={{ display: 'flex', flexWrap: 'wrap', margin: '-10px' }}>
            <Stat label="Total Messages" value={data.totalMessages.toLocaleString()} icon="💬" />
            <Stat label="Active Members" value={data.activeMembers.toLocaleString()} icon="👥" />
            <Stat label="Total Reactions" value={data.totalReactions.toLocaleString()} icon="🎭" />
            <Stat label="Top Emoji" value={data.topEmoji?.name || 'N/A'} icon="✨" />
          </div>
          
          <div style={{ display: 'flex', marginTop: '20px', gap: '20px' }}>
            <div style={{ display: 'flex', flexDirection: 'column', backgroundColor: 'rgba(88, 101, 242, 0.2)', padding: '20px', borderRadius: '16px', flex: 1 }}>
              <div style={{ display: 'flex', fontSize: '14px', color: '#B9BBBE', marginBottom: '4px' }}>Busiest Day</div>
              <div style={{ display: 'flex', fontSize: '24px', fontWeight: 'bold' }}>{data.busiestDay || 'N/A'}</div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', backgroundColor: 'rgba(88, 101, 242, 0.2)', padding: '20px', borderRadius: '16px', flex: 1 }}>
              <div style={{ display: 'flex', fontSize: '14px', color: '#B9BBBE', marginBottom: '4px' }}>Peak Hour</div>
              <div style={{ display: 'flex', fontSize: '24px', fontWeight: 'bold' }}>{data.peakHour !== null ? `${data.peakHour}:00` : 'N/A'}</div>
            </div>
          </div>
        </div>

        {/* Right Column: Top Users */}
        <div style={{ display: 'flex', flexDirection: 'column', width: '400px' }}>
          <SectionTitle>Most Active Members</SectionTitle>
          <div style={{ display: 'flex', flexDirection: 'column', backgroundColor: 'rgba(255, 255, 255, 0.05)', padding: '30px', borderRadius: '24px', flex: 1 }}>
            {data.topUsers.length > 0 ? (
              data.topUsers.map((user, index) => (
                <BarRow 
                  key={user.userId} 
                  label={`User ${index + 1}`} // We don't have usernames here, normally we'd fetch them or pass them
                  value={user.count} 
                  max={maxMessages}
                  color={index === 0 ? '#5865F2' : index === 1 ? '#43B581' : '#FAA61A'}
                />
              ))
            ) : (
              <div style={{ display: 'flex', color: '#B9BBBE' }}>No active members this period.</div>
            )}
            
            <div style={{ display: 'flex', marginTop: 'auto', paddingTop: '20px', borderTop: '1px solid rgba(255, 255, 255, 0.1)', fontSize: '14px', color: '#B9BBBE' }}>
              Based on total messages sent
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div style={{ display: 'flex', marginTop: '40px', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', color: '#B9BBBE', fontSize: '16px' }}>
          Generated by Discord Wrapped Bot
        </div>
        <div style={{ display: 'flex', backgroundColor: '#5865F2', padding: '8px 16px', borderRadius: '20px', fontSize: '14px', fontWeight: 'bold' }}>
          SPOTIFY STYLE
        </div>
      </div>
    </div>
  );
};
